#ifndef OCTOPUS_SETTING_H_
#define OCTOPUS_SETTING_H_

#define OCTOPUS_SAME_CARD_TIMEOUT       3000

#define OCTOPUS_SYSTEM_CODE             0x8008
#define OCTOPUS_REQUEST_CODE            0x01

#define OCTOPUS_BALANCE_SERVICE_CODE    0x117
#define OCTOPUS_BALANCE_SERVICE_BLOCK   0x8000

#endif